In [3]:
import pandas as pd
wind_df = pd.read_csv("Kelmarsh_1_selected.csv")

In [4]:
wind_df = wind_df.dropna(subset=['Wind speed, Standard deviation (m/s)', 'Wind speed, Minimum (m/s)', 'Wind speed, Maximum (m/s)'])
print(wind_df.head(5))

             Date and time  turbine_id  Wind speed (m/s)  \
38448  2017-09-25 00:00:00           1          5.171129
38449  2017-09-25 00:10:00           1          5.090679
38450  2017-09-25 00:20:00           1          5.193162
38451  2017-09-25 00:30:00           1          4.995740
38452  2017-09-25 00:40:00           1          5.111104

       Wind speed, Standard deviation (m/s)  Wind speed, Minimum (m/s)  \
38448                              0.390980                   4.240140
38449                              0.436131                   4.303428
38450                              0.305424                   4.739578
38451                              0.258361                   4.488607
38452                              0.296016                   4.674517

       Wind speed, Maximum (m/s)  Wind direction (°)  Nacelle position (°)  \
38448                   5.912565          151.294891            156.414673
38449                   5.930200          147.942764            156.414673
38450                   5.894996          153.931564            156.414673
38451                   5.601314          156.852936            156.414673
38452                   5.677069          160.317307            156.414673

       Blade angle (pitch position) A (°)  Blade angle (pitch position) B (°)  \
38448                                 0.0                                 0.0
38449                                 0.0                                 0.0
38450                                 0.0                                 0.0
38451                                 0.0                                 0.0
38452                                 0.0                                 0.0

       Blade angle (pitch position) C (°)  Rotor speed (RPM)  Power (kW)
38448                                 0.0           8.963050  200.121521
38449                                 0.0           8.942242  196.931503
38450                                 0.0           8.943247  197.651825
38451                                 0.0           8.759842  182.931046
38452                                 0.0           8.987873  202.370926

In [5]:
print(wind_df.isnull().sum())

Date and time                           0
turbine_id                              0
Wind speed (m/s)                        0
Wind speed, Standard deviation (m/s)    0
Wind speed, Minimum (m/s)               0
Wind speed, Maximum (m/s)               0
Wind direction (°)                      0
Nacelle position (°)                    0
Blade angle (pitch position) A (°)      0
Blade angle (pitch position) B (°)      0
Blade angle (pitch position) C (°)      0
Rotor speed (RPM)                       0
Power (kW)                              0
dtype: int64

In [6]:
wind_df.describe()

,turbine_id,Wind speed (m/s),"Wind speed, Standard deviation (m/s)","Wind speed, Minimum (m/s)","Wind speed, Maximum (m/s)",Wind direction (°),Nacelle position (°),Blade angle (pitch position) A (°),Blade angle (pitch position) B (°),Blade angle (pitch position) C (°),Rotor speed (RPM),Power (kW)
count,14104.0,14104.000000,14104.000000,14104.000000,14104.000000,14104.000000,14104.000000,14104.000000,14104.000000,14104.000000,14104.000000,14104.000000
mean,1.0,7.201321,0.910474,5.441557,8.924519,243.800715,243.908005,2.546973,2.548810,2.548497,11.938683,846.764506
std,0.0,2.686179,0.429770,2.190492,3.327839,64.520128,64.298128,8.626667,8.628781,8.632381,3.315064,658.075974
min,1.0,0.162881,0.000000,0.018750,0.322125,0.042586,0.232071,0.000000,0.000000,0.000000,0.000000,-11.275332
25%,1.0,5.336060,0.586903,3.933830,6.587963,216.472492,216.780731,0.000000,0.000000,0.000000,9.690037,276.258202
50%,1.0,7.038617,0.848856,5.384649,8.626714,249.273293,250.086922,0.000000,0.000000,0.000000,12.664424,682.983124
75%,1.0,8.952175,1.159225,6.862958,11.053311,285.908424,287.024353,0.764998,0.767628,0.764421,14.975741,1380.229706
max,1.0,17.587736,3.548490,14.105850,24.886189,359.968353,359.969177,92.489998,92.500000,92.940002,15.294918,2069.349854

In [8]:
lower_bound = 0 
upper_bound = 90

wind_df = wind_df[(wind_df['Blade angle (pitch position) A (°)'] >= 0) & (wind_df['Blade angle (pitch position) A (°)'] <= 90)]
wind_df = wind_df[wind_df['Power (kW)'] >= 0]
wind_df.describe()

,turbine_id,Wind speed (m/s),"Wind speed, Standard deviation (m/s)","Wind speed, Minimum (m/s)","Wind speed, Maximum (m/s)",Wind direction (°),Nacelle position (°),Blade angle (pitch position) A (°),Blade angle (pitch position) B (°),Blade angle (pitch position) C (°),Rotor speed (RPM),Power (kW)
count,13557.0,13557.000000,13557.000000,13557.000000,13557.000000,13557.000000,13557.000000,13557.000000,13557.000000,13557.000000,13557.000000,13557.000000
mean,1.0,7.405527,0.929151,5.609374,9.165548,245.438438,245.006927,1.035170,1.036771,1.036261,12.356639,881.012324
std,0.0,2.525168,0.425202,2.056596,3.152834,61.199683,61.468831,3.085604,3.087982,3.090468,2.591296,648.300497
min,1.0,1.829961,0.000000,0.393959,2.890489,0.042586,0.232071,0.000000,0.000000,0.000000,1.660104,0.295075
25%,1.0,5.545944,0.608628,4.141752,6.836043,217.448776,217.877258,0.000000,0.000000,0.000000,10.064557,315.474121
50%,1.0,7.170693,0.871423,5.484888,8.800173,249.383759,249.707672,0.000000,0.000000,0.000000,12.891629,724.026367
75%,1.0,9.052721,1.172534,6.941835,11.160933,285.270203,285.926270,0.527000,0.530424,0.530031,15.007724,1413.861206
max,1.0,17.587736,3.548490,14.105850,24.886189,359.968353,359.969177,85.077774,85.255295,85.979652,15.294918,2069.349854

In [10]:
wind_df['Date and time'] = pd.to_datetime(wind_df['Date and time']) 
print(wind_df.head(5))

            Date and time  turbine_id  Wind speed (m/s)  \
38448 2017-09-25 00:00:00           1          5.171129
38449 2017-09-25 00:10:00           1          5.090679
38450 2017-09-25 00:20:00           1          5.193162
38451 2017-09-25 00:30:00           1          4.995740
38452 2017-09-25 00:40:00           1          5.111104

       Wind speed, Standard deviation (m/s)  Wind speed, Minimum (m/s)  \
38448                              0.390980                   4.240140
38449                              0.436131                   4.303428
38450                              0.305424                   4.739578
38451                              0.258361                   4.488607
38452                              0.296016                   4.674517

       Wind speed, Maximum (m/s)  Wind direction (°)  Nacelle position (°)  \
38448                   5.912565          151.294891            156.414673
38449                   5.930200          147.942764            156.414673
38450                   5.894996          153.931564            156.414673
38451                   5.601314          156.852936            156.414673
38452                   5.677069          160.317307            156.414673

       Blade angle (pitch position) A (°)  Blade angle (pitch position) B (°)  \
38448                                 0.0                                 0.0
38449                                 0.0                                 0.0
38450                                 0.0                                 0.0
38451                                 0.0                                 0.0
38452                                 0.0                                 0.0

       Blade angle (pitch position) C (°)  Rotor speed (RPM)  Power (kW)
38448                                 0.0           8.963050  200.121521
38449                                 0.0           8.942242  196.931503
38450                                 0.0           8.943247  197.651825
38451                                 0.0           8.759842  182.931046
38452                                 0.0           8.987873  202.370926

In [11]:
wind_df[['Blade angle (pitch position) A (°)', 
    'Blade angle (pitch position) B (°)', 
    'Blade angle (pitch position) C (°)']].std(axis=1).describe() # checking if averaging is safe

count    13557.000000
mean         0.002114
std          0.008432
min          0.000000
25%          0.000000
50%          0.000000
75%          0.002598
max          0.577141
dtype: float64

In [ ]:
df['pitch_angle'] = df[['Blade angle (pitch position) A (°)', 'Blade angle (pitch position) B (°)', 'Blade angle (pitch position) C (°)']].mean(axis=1) # averaging the angles into one target column

In [19]:
operating_df = pd.read_csv("Status_Kelmarsh_1_2017-01-01_-_2018-01-01_228.csv", skiprows = 9)
print(operating_df.head(5))

       Timestamp start        Timestamp end   Duration         Status  Code  \
0  2016-12-17 16:38:07  2017-01-09 12:51:27  548:13:20        Warning  2125
1  2017-01-02 06:55:53  2017-01-02 06:58:10   00:02:17           Stop   710
2  2017-01-05 11:18:28  2017-01-05 11:19:15   00:00:47  Informational    10
3  2017-01-05 11:18:28  2017-01-05 11:28:29   00:10:01           Stop  5760
4  2017-01-07 01:16:37  2017-01-07 13:00:39   11:44:02  Communication  9997

                            Message  Comment  \
0              Timeout brake closed      NaN
1                      Battery test      NaN
2                 Wind < start wind      NaN
3  Hydraulic oil flushing operation      NaN
4    Data communication unavailable      NaN

             Service contract category                        IEC category
0                        Warnings (27)                                 NaN
1               Operating states  (28)                   Technical Standby
2  External stop (low wind speed)  (5)  Out of Environmental Specification
3               Operating states  (28)                   Technical Standby
4                                  NaN                                 NaN

In [21]:
operating_df.columns.tolist()

['Timestamp start',
 'Timestamp end',
 'Duration',
 'Status',
 'Code',
 'Message',
 'Comment',
 'Service contract category',
 'IEC category']

In [22]:
operating_df['Status'].value_counts()

Status
Informational    7133
Stop              149
Warning            62
Communication      21
Name: count, dtype: int64

In [25]:
operating_df['Timestamp start'] = pd.to_datetime(operating_df['Timestamp start'])
operating_df['Timestamp end'] = pd.to_datetime(operating_df['Timestamp end'], errors='coerce')
print(operating_df.head(5))

      Timestamp start       Timestamp end   Duration         Status  Code  \
0 2016-12-17 16:38:07 2017-01-09 12:51:27  548:13:20        Warning  2125
1 2017-01-02 06:55:53 2017-01-02 06:58:10   00:02:17           Stop   710
2 2017-01-05 11:18:28 2017-01-05 11:19:15   00:00:47  Informational    10
3 2017-01-05 11:18:28 2017-01-05 11:28:29   00:10:01           Stop  5760
4 2017-01-07 01:16:37 2017-01-07 13:00:39   11:44:02  Communication  9997

                            Message  Comment  \
0              Timeout brake closed      NaN
1                      Battery test      NaN
2                 Wind < start wind      NaN
3  Hydraulic oil flushing operation      NaN
4    Data communication unavailable      NaN

             Service contract category                        IEC category
0                        Warnings (27)                                 NaN
1               Operating states  (28)                   Technical Standby
2  External stop (low wind speed)  (5)  Out of Environmental Specification
3               Operating states  (28)                   Technical Standby
4                                  NaN                                 NaN

In [26]:
#flagging and excluding 'stop' periods
stop_periods = operating_df[operating_df['Status'] == 'Stop']

intervals = pd.IntervalIndex.from_arrays(
    stop_periods['Timestamp start'],
    stop_periods['Timestamp end'],
    closed = 'left'
)

wind_df['during_stop'] = wind_df['Date and time'].apply(lambda t: intervals.contains(t).any())

merged_df = wind_df[~wind_df['during_stop']].drop(columns='during_stop')

In [27]:
operating_df[operating_df['Status'] == 'Warning']['Message'].value_counts()

Message
Timeout brake closed                 15
Breakdown obstacle light             11
Comm. failure FPM                     9
Overload generator fan 1              3
Overload generator fan 2              3
Overload generator fan 3              3
Brake accumulator defect              3
Overload generator heating            2
Limit switch error 95° axis 1         2
Limit switch error 95° axis 3         2
Limit switch error 95° axis 2         1
Pitch measuring system 1><2           1
4-20mA anemometer 2                   1
4-20 mA vane 2                        1
Brake pads worn                       1
Battery charge cycle axis 1 error     1
Battery charge cycle axis 2 error     1
Battery charge cycle axis 3 error     1
Time sync. failed (SNTP error)        1
Name: count, dtype: int64

In [28]:
# 1. Make sure timestamps are parsed (coerce handles the "-" placeholder rows)
operating_df['Timestamp start'] = pd.to_datetime(operating_df['Timestamp start'], errors='coerce')
operating_df['Timestamp end'] = pd.to_datetime(operating_df['Timestamp end'], errors='coerce')
wind_df['Date and time'] = pd.to_datetime(wind_df['Date and time'])

# 2. Full stop periods — turbine wasn't producing at all
stop_periods = operating_df[operating_df['Status'] == 'Stop']

# 3. Warnings that are specifically pitch- or wind-sensor related
exclude_keywords = ['Limit switch', 'Pitch measuring', 'anemometer', 'vane', 'Battery charge cycle']
pitch_related_warnings = operating_df[
    (operating_df['Status'] == 'Warning') &
    (operating_df['Message'].str.contains('|'.join(exclude_keywords), case=False, na=False))
]

# 4. Combine both into one exclusion set, drop rows with no valid end timestamp
exclude_periods = pd.concat([stop_periods, pitch_related_warnings]).dropna(subset=['Timestamp start', 'Timestamp end'])

# 5. Build an interval index and flag any wind_df row that falls inside an excluded period
intervals = pd.IntervalIndex.from_arrays(
    exclude_periods['Timestamp start'],
    exclude_periods['Timestamp end'],
    closed='left'
)
wind_df['excluded'] = wind_df['Date and time'].apply(lambda t: intervals.contains(t).any())

# 6. Final cleaned dataframe
merged_df = wind_df[~wind_df['excluded']].drop(columns='excluded')

print(f"Original rows: {len(wind_df)}")
print(f"Excluded rows: {wind_df['excluded'].sum()}")
print(f"Remaining rows: {len(merged_df)}")

Original rows: 13557
Excluded rows: 6
Remaining rows: 13551

In [32]:
merged_df.columns.tolist()

['Date and time',
 'turbine_id',
 'Wind speed (m/s)',
 'Wind speed, Standard deviation (m/s)',
 'Wind speed, Minimum (m/s)',
 'Wind speed, Maximum (m/s)',
 'Wind direction (°)',
 'Nacelle position (°)',
 'Rotor speed (RPM)',
 'Power (kW)',
 'during_stop',
 'pitch_angle']

In [33]:
merged_df.isnull().sum()

Date and time                           0
turbine_id                              0
Wind speed (m/s)                        0
Wind speed, Standard deviation (m/s)    0
Wind speed, Minimum (m/s)               0
Wind speed, Maximum (m/s)               0
Wind direction (°)                      0
Nacelle position (°)                    0
Rotor speed (RPM)                       0
Power (kW)                              0
during_stop                             0
pitch_angle                             0
dtype: int64

In [34]:
merged_df.to_csv("Kelmarsh_wrangled.csv", index=False)